-- 1.Tạo database tên BAITHI gồm có 4 table KHACHHANG, LOAICAY, HOADON, CTHD. Tạo khóa chính, khóa ngoại cho các table đó (2đ).
CREATE DATABASE BAITHI
GO
USE BAITHI
GO
CREATE TABLE KHACHHANG (
MAKH CHAR(4) NOT NULL,
TENKH VARCHAR(30),
DIACHI VARCHAR(30),
LOAIKH VARCHAR(20),
CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)
GO
CREATE TABLE LOAICAY (
MALC CHAR(4) NOT NULL,
TENLC VARCHAR(30),
XUATXU VARCHAR(30),
GIA MONEY,
CONSTRAINT PK_LOAICAY PRIMARY KEY(MALC)
)
GO
CREATE TABLE HOADON (
SOHD INT NOT NULL,
NGHD SMALLDATETIME,
MAKH CHAR(4),
KHUYENMAI INT,
CONSTRAINT PK_HOADON PRIMARY KEY(SOHD),
CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)
GO
CREATE TABLE CTHD (
SOHD INT NOT NULL,
MALC CHAR(4) NOT NULL,
SOLUONG INT,
CONSTRAINT PK_CTHD PRIMARY KEY(SOHD,MALC),
CONSTRAINT FK_CTHD_HOADON FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD),
CONSTRAINT FK_CTHD_LOAICAY FOREIGN KEY(MALC) REFERENCES LOAICAY(MALC)
)

--2. Nhập dữ liệu cho 4 table như đề bài (1đ).
INSERT INTO KHACHHANG(MAKH, TENKH, DIACHI, LOAIKH) VALUES ('KH01','Liz Kim Cuong', 'Ha Noi','Vang lai')
INSERT INTO KHACHHANG(MAKH, TENKH, DIACHI, LOAIKH) VALUES ('KH02','Ivone Dieu Linh', 'Da Nang','Thuong xuyen')
INSERT INTO KHACHHANG(MAKH, TENKH, DIACHI, LOAIKH) VALUES ('KH03','Emma Nhat Khanh', 'TP.HCM','Vang lai')

INSERT INTO LOAICAY(MALC, TENLC, XUATXU, GIA) VALUES ('LC01', 'Xuong rong tai tho', 'Mexico', 180000)
INSERT INTO LOAICAY(MALC, TENLC, XUATXU, GIA) VALUES ('LC02', 'Sen thach ngoc', 'Anh', 300000)
INSERT INTO LOAICAY(MALC, TENLC, XUATXU, GIA) VALUES ('LC03', 'Ba mau rau', 'Nam Phi', 270000)

INSERT INTO HOADON(SOHD, NGHD, MAKH, KHUYENMAI) VALUES ('00001', 22/11/2017 ,'KH01',5)
INSERT INTO HOADON(SOHD, NGHD, MAKH, KHUYENMAI) VALUES ('00002',04/12/2017,'KH03',5)
INSERT INTO HOADON(SOHD, NGHD, MAKH, KHUYENMAI) VALUES ('00003',10/12/2017,'KH02',10)

INSERT INTO CTHD(SOHD, MALC, SOLUONG) VALUES ('00001', 'LC01', 1)
INSERT INTO CTHD(SOHD, MALC, SOLUONG) VALUES ('00001', 'LC02', 2)
INSERT INTO CTHD(SOHD, MALC, SOLUONG) VALUES ('00003', 'LC03', 5)


--3. Hiện thực ràng buộc toàn vẹn sau: Tất cả các mặt hàng xuất xứ từ nước Anh đều có giá lớn hơn 250.000đ
--   THEM   XOA    SUA
--LC  +       -      +(XUATXU, GIA)
CREATE TRIGGER TRG_INSERT_UPDATE_LOAICAY_XUATXU_GIA ON LOAICAY
FOR INSERT, UPDATE
AS
BEGIN
IF EXISTS(
   SELECT * FROM INSERTED
   WHERE INSERTED.XUATXU= 'Anh' AND INSERTED.GIA <= 250000)
      BEGIN
      PRINT 'LOI: GIA KHONG HOP LE'
      ROLLBACK TRANSACTION
      END
ELSE
   BEGIN
   PRINT 'THEM/SUA LOAICAY THANH CONG'
   END
END

GO

--4. Hiện thực ràng buộc toàn vẹn sau: Hóa đơn mua với số lượng tổng cộng lớn hơn hoặc bằng 5 đều được giảm giá 10 phần trăm. (2đ).
--        THEM    XOA    SUA
--CTHD      +      -      +(SOLUONG)
--HOADON    -      -      +(KHUYENMAI)

CREATE TRIGGER TRG_INSERT_UPDATE_CTHD_SOLUONG ON CTHD
FOR INSERT, UPDATE
AS
BEGIN
    UPDATE HOADON
	SET KHUYENMAI=10
	FROM HOADON HD
	JOIN INSERTED INS ON INS.SOHD=HD.SOHD
	WHERE INS.SOHD IN (
	SELECT CT1.SOHD
	FROM DBO.CTHD CT1
	JOIN INSERTED INS2 ON INS2.SOHD=CT1.SOHD
	GROUP BY CT1.SOHD
	HAVING SUM(CT1.SOLUONG)>=5
	)
	PRINT 'DA CAP NHAT KHUYENMAI HOADON'
END
GO

CREATE TRIGGER TRG_UPDATE_HOADON_KHUYENMAI ON HOADON
FOR UPDATE
AS
BEGIN
   IF EXISTS(
   SELECT *
   FROM INSERTED INS
   WHERE INS.SOHD IN (
      SELECT CT.SOHD
      FROM CTHD CT
      GROUP BY CT.SOHD
      HAVING SUM(CT.SOLUONG)>=5
      ) AND INS.KHUYENMAI!=10   
   )
   BEGIN
   PRINT 'LOI: KHUYENMAI KHONG HOP LE'
   ROLLBACK TRANSACTION
   END
   ELSE
   BEGIN
   PRINT 'UPDATE THANH CONG'
   END
END

--5. Tìm tất cả các hóa đơn có ngày lập hóa đơn trong quý 4 năm 2017, sắp xếp kết quả tăng dần theo phần trăm giảm giá (1đ).
SELECT * FROM HOADON
WHERE MONTH(NGHD) BETWEEN 10 AND 12
ORDER BY KHUYENMAI
--6. Tìm loại cây có số lượng mua ít nhất trong tháng 12 (1đ).
SELECT * FROM DBO.LOAICAY
WHERE LOAICAY.MALC IN (
SELECT TOP 1 WITH TIES MALC
FROM DBO.CTHD
GROUP BY MALC
ORDER BY SUM(SOLUONG)
)
--7. Tìm loại cây mà cả khách thường xuyên (LOAIKH là ‘Thuong xuyen’) và khách vãng lai (LOAIKH là ‘Vang lai’) đều mua. (1đ).
SELECT * FROM LOAICAY
WHERE LOAICAY.MALC IN (
(SELECT MALC
FROM DBO.HOADON HD
     JOIN DBO.KHACHHANG KH ON HD.MAKH=KH.MAKH
	 JOIN DBO.CTHD CT ON CT.SOHD=HD.SOHD
WHERE LOAIKH='Vang lai'
)
INTERSECT
(
SELECT MALC
FROM DBO.HOADON HD
     JOIN DBO.KHACHHANG KH ON HD.MAKH=KH.MAKH
	 JOIN DBO.CTHD CT ON CT.SOHD=HD.SOHD
WHERE LOAIKH='Thuong xuyen'
)
)
--8. Tìm khách hàng đã từng mua tất cả các loại cây (1đ).
SELECT * FROM KHACHHANG	
WHERE KHACHHANG.MAKH IN (
SELECT MAKH
FROM DBO.HOADON HD 
     JOIN DBO.CTHD CT ON CT.SOHD=HD.SOHD
GROUP BY MAKH
HAVING COUNT(DISTINCT MALC) = (
SELECT COUNT(MALC)
FROM LOAICAY
)
)