-------------- BAI TAP 2----------------
--19.	Khoa nào (mã khoa, tên khoa) được thành lập sớm nhất.
SELECT TOP 1 WITH TIES MAKHOA, TENKHOA
FROM DBO.KHOA
ORDER BY NGTLAP
--20.	Có bao nhiêu giáo viên có học hàm là “GS” hoặc “PGS”.
SELECT COUNT(GV.MAGV) AS [SO GIAO VIEN]
FROM DBO.GIAOVIEN AS GV
WHERE GV.HOCHAM= 'GS' OR GV.HOCHAM = 'PGS'

--21.	Thống kê có bao nhiêu giáo viên có học vị là “CN”, “KS”, “Ths”, “TS”, “PTS” trong mỗi khoa.
SELECT GV.MAKHOA, COUNT(GV.MAGV) AS [SO GIAO VIEN]
FROM DBO.GIAOVIEN AS GV
GROUP BY GV.MAKHOA

--22.	Mỗi môn học thống kê số lượng học viên theo kết quả (đạt và không đạt).
SELECT KQ1.MAMH, KQ1.KQUA, COUNT(KQ1.MAHV) AS [SO LUONG]
FROM DBO.KETQUATHI AS KQ1
WHERE KQ1.LANTHI >= ALL (
SELECT KQ2.LANTHI
FROM DBO.KETQUATHI AS KQ2
WHERE KQ2.MAHV = KQ1.MAHV AND KQ2.MAMH = KQ2.MAMH
)
GROUP BY KQ1.MAMH, KQ1.KQUA
ORDER BY KQ1.MAMH

--23.	Tìm giáo viên (mã giáo viên, họ tên) là giáo viên chủ nhiệm của một lớp, đồng thời dạy cho lớp đó ít nhất một môn học.
SELECT GV.MAGV, GV.HOTEN, LOP.MALOP
FROM DBO.LOP AS LOP
     JOIN DBO.GIAOVIEN AS GV ON GV.MAGV= LOP.MAGVCN
WHERE LOP.MAGVCN IN (
SELECT GD.MAGV
FROM DBO.GIANGDAY AS GD
WHERE GD.MALOP= LOP.MALOP
)
--24.	Tìm họ tên lớp trưởng của lớp có sỉ số cao nhất.
SELECT TOP 1 HV.HO+' '+HV.TEN AS [LOP TRUONG]
FROM DBO.LOP AS LOP
     JOIN DBO.HOCVIEN AS HV ON HV.MAHV= LOP.TRGLOP
ORDER BY LOP.SISO DESC
--25.	* Tìm họ tên những LOPTRG thi không đạt quá 3 môn (mỗi môn đều thi không đạt ở tất cả các lần thi).
SELECT HV.HO+' '+HV.TEN AS [HO TEN]
FROM DBO.LOP AS LOP
     JOIN DBO.HOCVIEN AS HV ON HV.MAHV=LOP.TRGLOP
WHERE LOP.TRGLOP IN(
SELECT KQ1.MAHV
FROM DBO.KETQUATHI AS KQ1
WHERE KQ1.LANTHI >= ALL (
SELECT KQ2.LANTHI
FROM DBO.KETQUATHI AS KQ2
WHERE KQ2.MAHV= KQ1.MAHV AND KQ2.MAMH=KQ1.MAMH
) AND KQ1.KQUA='Khong Dat'
GROUP BY KQ1.MAHV
HAVING COUNT(KQ1.MAMH) > 3
)

-------------- BAI TAP 4 ----------------
--26.	Tìm học viên (mã học viên, họ tên) có số môn đạt điểm 9, 10 nhiều nhất.
SELECT HV.MAHV, HO+' '+HV.TEN AS [HO TEN]
FROM DBO.HOCVIEN AS HV
WHERE HV.MAHV IN(
SELECT TOP 1 KQ1.MAHV
FROM DBO.KETQUATHI AS KQ1
WHERE KQ1.DIEM=9 OR KQ1.DIEM=10
GROUP BY KQ1.MAHV
ORDER BY COUNT(KQ1.MAMH) DESC
)
--27.	Trong từng lớp, tìm học viên (mã học viên, họ tên) có số môn đạt điểm 9, 10 nhiều nhất.
SELECT LEFT(A.MAHV, 3) MALOP, A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, RANK () OVER (ORDER BY COUNT(MAMH) DESC) RANK_MH FROM KETQUATHI KQ 
	WHERE DIEM BETWEEN 9 AND 10
	GROUP BY KQ.MAHV
) A JOIN HOCVIEN AS HV
ON A.MAHV = HV.MAHV
WHERE RANK_MH = 1
GROUP BY LEFT(A.MAHV, 3), A.MAHV, HO, TEN

--28.	Trong từng học kỳ của từng năm, mỗi giáo viên phân công dạy bao nhiêu môn học, bao nhiêu lớp.
SELECT GD.NAM, GD.HOCKY, GD.MAGV, COUNT(DISTINCT GD.MAMH) AS [MON HOC], COUNT(DISTINCT GD.MALOP) AS [LOP]
FROM DBO.GIANGDAY AS GD
GROUP BY GD.NAM,GD.HOCKY, GD.MAGV
--29.	Trong từng học kỳ của từng năm, tìm giáo viên (mã giáo viên, họ tên) giảng dạy nhiều nhất.
SELECT GD.NAM, GD.HOCKY, GD.MAGV
FROM DBO.GIANGDAY AS GD
GROUP BY GD.NAM,GD.HOCKY, GD.MAGV
HAVING GD.MAGV IN (
SELECT TOP 1 GD1.MAGV
FROM DBO.GIANGDAY AS GD1
GROUP BY GD1.NAM,GD1.HOCKY, GD1.MAGV
HAVING GD1.NAM=GD.NAM AND GD1.HOCKY=GD.HOCKY
ORDER BY COUNT(GD1.MAMH) DESC
)
--30.	Tìm môn học (mã môn học, tên môn học) có nhiều học viên thi không đạt (ở lần thi thứ 1) nhất.
SELECT MH.MAMH, MH.TENMH
FROM DBO.MONHOC AS MH
WHERE MH.MAMH IN(
SELECT TOP 1 KQ.MAMH
FROM DBO.KETQUATHI AS KQ
WHERE KQ.LANTHI=1 AND KQ.KQUA='Khong Dat'
GROUP BY KQ.MAMH
ORDER BY COUNT(KQ.MAHV) DESC)
--31.	Tìm học viên (mã học viên, họ tên) thi môn nào cũng đạt (chỉ xét lần thi thứ 1).
SELECT HV.MAHV
FROM DBO.HOCVIEN AS HV
WHERE HV.MAHV NOT IN (
SELECT KQ.MAHV
FROM DBO.KETQUATHI AS KQ
WHERE KQ.KQUA='Khong Dat'
)


--32.	* Tìm học viên (mã học viên, họ tên) thi môn nào cũng đạt (chỉ xét lần thi sau cùng).
SELECT HV.MAHV, HV.HO+' '+HV.TEN AS [HO TEN]
FROM DBO.HOCVIEN AS HV
WHERE HV.MAHV NOT IN (
SELECT KQ.MAHV
FROM DBO.KETQUATHI AS KQ
WHERE KQ.KQUA='Khong Dat' AND KQ.LANTHI >= ALL(
SELECT KQ1.LANTHI
FROM DBO.KETQUATHI AS KQ1
WHERE KQ1.MAHV=KQ.MAHV AND KQ1.MAMH=KQ.MAMH
)
)
--33.	* Tìm học viên (mã học viên, họ tên) đã thi tất cả các môn và đều đạt (chỉ xét lần thi thứ 1).
SELECT HV.MAHV
FROM DBO.HOCVIEN AS HV
WHERE HV.MAHV NOT IN (
SELECT KQ.MAHV
FROM DBO.KETQUATHI AS KQ
WHERE KQ.KQUA='Khong Dat'
) AND HV.MAHV IN (
SELECT KQ1.MAHV
FROM DBO.KETQUATHI AS KQ1
GROUP BY KQ1.MAHV
HAVING COUNT(DISTINCT KQ1.MAMH) >= ALL (
SELECT COUNT(MONHOC.MAMH)
FROM DBO.MONHOC
)
)
--34.	* Tìm học viên (mã học viên, họ tên) đã thi tất cả các môn và đều đạt (chỉ xét lần thi sau cùng).
SELECT HV.MAHV
FROM DBO.HOCVIEN AS HV
WHERE HV.MAHV NOT IN (
SELECT KQ.MAHV
FROM DBO.KETQUATHI AS KQ
WHERE KQ.KQUA='Khong Dat' AND KQ.LANTHI >= ALL (
SELECT KQ2.LANTHI
FROM DBO.KETQUATHI AS KQ2
WHERE KQ2.MAHV=KQ.MAHV AND KQ2.MAMH=KQ.MAMH
)
) AND HV.MAHV IN (
SELECT KQ1.MAHV
FROM DBO.KETQUATHI AS KQ1
GROUP BY KQ1.MAHV
HAVING COUNT(DISTINCT KQ1.MAMH) >= ALL (
SELECT COUNT(MONHOC.MAMH)
FROM DBO.MONHOC
)
)
--35.	** Tìm học viên (mã học viên, họ tên) có điểm thi cao nhất trong từng môn (lấy điểm ở lần thi sau cùng).
SELECT TABLE1.MAMH, HV.MAHV, HV.HO+' '+HV.TEN AS [HOTEN], TABLE1.DIEMCAONHAT
FROM DBO.HOCVIEN AS HV
     JOIN
(SELECT KQ.MAMH, KQ.MAHV, MAX(KQ.DIEM) AS [DIEMCAONHAT]
FROM DBO.KETQUATHI AS KQ
WHERE KQ.LANTHI >= ALL (
SELECT KQ1.LANTHI
FROM DBO.KETQUATHI AS KQ1
WHERE KQ1.MAHV=KQ.MAHV AND KQ1.MAMH=KQ.MAMH
)
GROUP BY KQ.MAMH,KQ.MAHV
HAVING MAX(KQ.DIEM) >=ALL (
SELECT MAX(KQ2.DIEM) AS [DIEMCAONHAT]
FROM DBO.KETQUATHI AS KQ2
WHERE KQ2.LANTHI >= ALL (
SELECT KQ3.LANTHI
FROM DBO.KETQUATHI AS KQ3
WHERE KQ3.MAHV=KQ2.MAHV AND KQ3.MAMH=KQ2.MAMH
) AND KQ2.MAMH= KQ.MAMH
GROUP BY KQ2.MAMH
)) TABLE1 ON TABLE1.MAHV= HV.MAHV