
-- CAU 1
CREATE DATABASE QUANLYSINHVIEN
GO
USE QUANLYSINHVIEN
GO

CREATE TABLE TOCHUC (
MADV CHAR(5) NOT NULL,
TENDV NVARCHAR(30),
EMAIL VARCHAR(30),
CONSTRAINT PK_TOCHUC PRIMARY KEY(MADV)
)

CREATE TABLE HOATDONG (
MAHD CHAR(5) NOT NULL,
TENHD NVARCHAR(30),
DIEM FLOAT,
NGAYTC DATETIME,
MADV CHAR(5),
CONSTRAINT PK_HOATDONG PRIMARY KEY(MAHD),
CONSTRAINT FK_HOATDONG_TOCHUC FOREIGN KEY(MADV) REFERENCES TOCHUC(MADV)
)
GO
CREATE TABLE SINHVIEN (
MASV CHAR(8) NOT NULL,
HOTEN NVARCHAR(30),
KHOA NVARCHAR(30),
NGAYSINH DATETIME,
GIOITINH NVARCHAR(3),
NAMVAOTRUONG INT,
CONSTRAINT PK_SINHVIEN PRIMARY KEY(MASV)
)
GO
CREATE TABLE BANGDIEM(
MASV CHAR(8) NOT NULL,
MAHD CHAR(5) NOT NULL,
CONSTRAINT PK_BANGDIEM PRIMARY KEY(MASV,MAHD),
CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
CONSTRAINT FK_BANGDIEM_HOATDONG FOREIGN KEY(MAHD) REFERENCES HOATDONG(MAHD)
)
GO
-- CAU 2
-- a.
--          THEM    XOA    SUA
--HOATDONG    +      -      +(DIEM)
CREATE TRIGGER TRG_INSERT_UPDATE_HOATDONG_DIEM ON HOATDONG
FOR INSERT, UPDATE
AS
BEGIN
      IF EXISTS(SELECT * FROM INSERTED INS
	            WHERE INS.DIEM>5 OR INS.DIEM <1
	          )
			  BEGIN
			  PRINT 'LOI: DIEM KHONG HOP LE'
			  ROLLBACK TRANSACTION
			  END
	ELSE
	BEGIN
	PRINT 'THEM/SUA THANH CONG'
	END
END
GO
-- TEST: INSERT INTO HOATDONG(MAHD, TENHD, DIEM, NGAYTC, MADV) VALUES ('HD001','HOAT DONG 1', 5.1, 31/12/2023, 'DV001')

--  b.
--           THEM  XOA  SUA
--BANGDIEM     +    -    +
CREATE TRIGGER TRG_INSERT_UPDATE_BANGDIEM_SVNAM5 ON BANGDIEM
FOR INSERT, UPDATE
AS
BEGIN
       IF EXISTS(
	             SELECT * FROM INSERTED INS JOIN SINHVIEN SV ON SV.MASV=INS.MASV JOIN HOATDONG HD ON HD.MAHD=INS.MAHD
				 WHERE (YEAR(HD.NGAYTC)- SV.NAMVAOTRUONG=4)	 
	            )
				BEGIN
				PRINT 'LOI: SINH VIEN NAM 5 KHONG DUOC THAM GIA HD MOI'
				ROLLBACK TRANSACTION
				END
		ELSE
		BEGIN
		PRINT 'THEM/SUA THANHCONG'
		END
END
GO

-- CAU 3
--a
SELECT SV.HOTEN, SUM(HD.DIEM) AS [DIEMRENLUYEN]
FROM BANGDIEM BD JOIN HOATDONG HD ON HD.MAHD=BD.MAHD JOIN SINHVIEN SV ON SV.MASV=BD.MASV
GROUP BY SV.HOTEN
HAVING SV.HOTEN='Nguyen Van A'

--b
SELECT SV.MASV, SV.HOTEN
FROM BANGDIEM BD JOIN HOATDONG HD ON HD.MAHD=BD.MAHD JOIN SINHVIEN SV ON SV.MASV=BD.MASV
WHERE (YEAR(HD.NGAYTC)-SV.NAMVAOTRUONG=3)
GROUP BY SV.MASV, SV.HOTEN
ORDER BY SV.MASV

--C
SELECT TOP 1 WITH TIES BD.MASV, SV.HOTEN, SV.KHOA
FROM BANGDIEM BD JOIN SINHVIEN SV ON SV.MASV=BD.MASV
GROUP BY BD.MASV, SV.HOTEN, SV.KHOA
ORDER BY COUNT(BD.MAHD) DESC

--d
SELECT BD.MASV, SV.HOTEN, SV.KHOA
FROM BANGDIEM BD JOIN HOATDONG HD ON HD.MAHD=BD.MAHD JOIN SINHVIEN SV ON SV.MASV=BD.MASV
WHERE SV.KHOA='KTMT' AND HD.TENHD='NGAY HOI CHAO TSV'
GROUP BY BD.MASV, SV.HOTEN, SV.KHOA

-- e
SELECT TOP 1 WITH TIES HD.MADV, TC.TENDV, COUNT(HD.MAHD) AS [SO HOAT DONG]
FROM HOATDONG HD JOIN TOCHUC TC ON HD.MADV=TC.MADV
GROUP BY HD.MADV, TC.TENDV
ORDER BY COUNT(HD.MAHD) DESC

-- f
SELECT * FROM SINHVIEN WHERE SINHVIEN.MASV IN (
SELECT BD.MASV
FROM BANGDIEM BD JOIN SINHVIEN SV ON BD.MASV=SV.MASV
GROUP BY BD.MASV
HAVING COUNT(BD.MAHD) = (
SELECT COUNT(HOATDONG.MAHD) FROM HOATDONG
)
)