                                              ----QUANLYBANHANG----

CREATE DATABASE QUANLYBANHANG
GO

USE QUANLYBANHANG
GO

CREATE TABLE KHACHHANG(
MAKH CHAR(4) NOT NULL,
HOTEN VARCHAR(40),
DCHI VARCHAR(50),
SODT VARCHAR(20),
NGSINH smalldatetime,
NGDK smalldatetime,
DOANHSO money,
CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)
GO

CREATE TABLE NHANVIEN(
MANV CHAR(4) NOT NULL,
HOTEN VARCHAR(40),
SODT VARCHAR(20),
NGVL SMALLDATETIME,
CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
)
GO

CREATE TABLE SANPHAM(
MASP CHAR(4) NOT NULL,
TENSP VARCHAR(40),
DVT VARCHAR(20),
NUOCSX VARCHAR(40),
GIA MONEY
CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)
)
GO

CREATE TABLE HOADON(
SOHD INT NOT NULL,
NGHD SMALLDATETIME,
MAKH CHAR(4),
MANV CHAR(4),
TRIGIA MONEY,
CONSTRAINT PK_HOADON PRIMARY KEY (SOHD)
)
GO


CREATE TABLE CTHD
(
	SOHD INT,
	MASP CHAR(4),
	SL INT,
	CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP)
)
GO
ALTER TABLE HOADON ADD
CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTHD ADD
CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
--2. Thêm vào thuộc tính GHICHU có kiểu dữ liệu varchar(20) cho quan hệ SANPHAM
ALTER TABLE SANPHAM ADD
GHICHU VARCHAR(20)
GO

--3. Thêm vào thuộc tính LOAIKH có kiểu dữ liệu là tinyint cho quan hệ KHACHHANG
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT
GO
--4. Sửa kiểu dữ liệu của thuộc tính GHICHU trong quan hệ SANPHAM thành varchar(100).
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100)
GO

--5. Xóa thuộc tính GHICHU trong quan hệ SANPHAM.
ALTER TABLE SANPHAM
DROP COLUMN GHICHU
GO

--6. Làm thế nào để thuộc tính LOAIKH trong quan hệ KHACHHANG có thể lưu các giá trị là: “Vang lai”, “Thuong xuyen”, “Vip”…
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(20)
GO

--7. Đơn vị tính của sản phẩm chỉ có thể là (“cay”,”hop”,”cai”,”quyen”,”chuc”)
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DVT CHECK(DVT in ('cay', 'hop', 'cai', 'quyen','chuc'))
GO

--8. Giá bán của sản phẩm từ 500 đồng trở lên.
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GIA CHECK(GIA >=500)
GO

--9. Mỗi lần mua hàng, khách hàng phải mua ít nhất 1 sản phẩm
ALTER TABLE CTHD
ADD CONSTRAINT CK_SL CHECK(SL>0)
GO

-- 10. Ngày khách hàng đăng ký là khách hàng thành viên phải lớn hơn ngày sinh của người đó.
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGDK CHECK(NGDK>NGSINH)
GO

                                             ----- QUANLYGIAOVU ------
CREATE DATABASE QUANLYGIAOVU
GO

USE QUANLYGIAOVU
GO

CREATE TABLE KHOA (
MAKHOA VARCHAR(4) NOT NULL,
TENKHOA VARCHAR(40),
NGTLAP SMALLDATETIME,
TRGKHOA CHAR(4),
CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
)
GO

CREATE TABLE MONHOC (
MAMH VARCHAR(10) NOT NULL,
TENMH VARCHAR(40),
TCLT TINYINT,
TCTH TINYINT,
MAKHOA VARCHAR(4),
CONSTRAINT PK_MONHOC PRIMARY KEY(MAMH)
)
GO

CREATE TABLE DIEUKIEN(
MAMH VARCHAR(10) NOT NULL,
MAMH_TRUOC VARCHAR(10) NOT NULL,
CONSTRAINT PK_DIEUKIEN PRIMARY KEY(MAMH, MAMH_TRUOC)
)
GO

CREATE TABLE GIAOVIEN(
MAGV CHAR(4) NOT NULL,
HOTEN VARCHAR(40),
HOCVI VARCHAR(10),
HOCHAM VARCHAR(10),
GIOITINH VARCHAR(3),
NGSINH SMALLDATETIME,
NGVL SMALLDATETIME,
HESO NUMERIC(4,2),
MUCLUONG MONEY,
MAKHOA VARCHAR(4),
CONSTRAINT PK_GIAOVIEN PRIMARY KEY(MAGV)
)
GO

CREATE TABLE LOP(
MALOP CHAR(3) NOT NULL,
TENLOP VARCHAR(40),
TRGLOP CHAR(5),
SISO TINYINT,
MAGVCN CHAR(4),
CONSTRAINT PK_LOP PRIMARY KEY(MALOP)
)
GO

CREATE TABLE HOCVIEN
(
MAHV CHAR(5) NOT NULL,
HO VARCHAR(40),
TEN VARCHAR(10),
NGSINH SMALLDATETIME,
GIOITINH VARCHAR(3),
NOISINH VARCHAR(40),
MALOP CHAR(3)
CONSTRAINT PK_HOCVIEN PRIMARY KEY(MAHV)
) 
GO

CREATE TABLE GIANGDAY
(
MALOP CHAR(3) NOT NULL,
MAMH VARCHAR(10) NOT NULL,
MAGV CHAR(4),
HOCKY TINYINT,
NAM SMALLINT,
TUNGAY SMALLDATETIME,
DENNGAY SMALLDATETIME,
CONSTRAINT PK_GIANGDAY PRIMARY KEY(MALOP, MAMH)
) 
GO

CREATE TABLE KETQUATHI
(
MAHV CHAR(5) NOT NULL,
MAMH VARCHAR(10) NOT NULL,
LANTHI TINYINT NOT NULL,
NGTHI SMALLDATETIME,
DIEM NUMERIC(4,2),
KQUA VARCHAR(10),
CONSTRAINT PK_KQTHI PRIMARY KEY(MAHV, MAMH, LANTHI)
)
GO

-- 2. * Mã học viên là một chuỗi 5 ký tự, 3 ký tự đầu là mã lớp, 2 ký tự cuối cùng là số thứ tự học viên trong lớp. VD: “K1101”
CREATE FUNCTION check_MALOP (@MAHV VARCHAR(5))
RETURNs TINYINT
AS 
BEGIN
	IF LEFT(@MAHV, 3) IN (SELECT MALOP FROM LOP)
		RETURN 1
	RETURN 0
END
GO

CREATE FUNCTION check_STT (@MAHV VARCHAR(5), @MALOP_HOCVIEN VARCHAR(3))
RETURNs TINYINT
AS
BEGIN
    IF RIGHT(@MAHV, 2) BETWEEN 1 AND (SELECT SISO FROM LOP WHERE MALOP = @MALOP_HOCVIEN)
		RETURN 1
	RETURN 0
END
GO

ALTER TABLE HOCVIEN ADD CONSTRAINT CK_MAHV CHECK( LEN(MAHV) = 5 AND dbo.check_MALOP(MAHV) = 1 AND dbo.check_STT(MAHV, MALOP) = 1 )
GO

-- 3. Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”.
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GIOITINHGV CHECK(GIOITINH in ('Nam', 'Nu'))
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GIOITINHHV CHECK(GIOITINH in ('Nam', 'Nu'))
GO

-- 4. Điểm số của một lần thi có giá trị từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22).
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_DIEM CHECK( DIEM BETWEEN 0 AND 10 AND LEN(SUBSTRING(CAST(DIEM AS VARCHAR), CHARINDEX('.', DIEM) + 1, 1000)) >= 2)
GO
-- 5. Kết quả thi là “Dat” nếu điểm từ 5 đến 10  và “Khong dat” nếu điểm nhỏ hơn 5

ALTER TABLE KETQUATHI ADD CONSTRAINT CK_KQUA CHECK(KQUA = CASE 
                                                          WHEN DIEM BETWEEN 5 AND 10 THEN 'Dat'
														  ELSE 'Khong dat'
														  END)
GO

-- 6. Học viên thi một môn tối đa 3 lần.
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_LANTHI CHECK(LANTHI <= 3)
GO
-- 7.Học kỳ chỉ có giá trị từ 1 đến 3.
ALTER TABLE GIANGDAY ADD CONSTRAINT CK_HOCKY CHECK(HOCKY BETWEEN 1 AND 3)
GO
-- 8. Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”.
ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_HOCVI CHECK(HOCVI IN ('CN','KS','Ths','TS','PTS'))
GO
