------1
SELECT DISTINCT COUNT(SP.MASP) AS [SO SAN PHAM KHAC NHAU BAN TRONG NAM 2020]
FROM DBO.SANPHAM AS SP
     JOIN CTHD ON SP.MASP= CTHD.MASP
	 JOIN HOADON HD ON HD.SOHD=CTHD.SOHD
WHERE YEAR(HD.NGHD)=2020

-----2
SELECT MIN(HD.TRIGIA) AS [TRI GIA THAP NHAT], MAX(HD.TRIGIA) AS [TRI GIA CAO NHAT]
FROM DBO.HOADON AS HD

----- 3
SELECT AVG(HD.TRIGIA) AS [TRI GIA TRUNG BINH NAM 2020]
FROM DBO.HOADON AS HD
WHERE YEAR(HD.NGHD)=2020

----- 4
SELECT SUM(HD.TRIGIA) AS [DOANH THU BAN HANG NAM 2020]
FROM DBO.HOADON AS HD
WHERE YEAR(HD.NGHD)=2020

----- 5
SELECT HD.SOHD
FROM DBO.HOADON AS HD
WHERE YEAR(HD.NGHD)=2020 AND HD.TRIGIA >= ALL(
SELECT HD.TRIGIA
FROM DBO.HOADON AS HD
WHERE YEAR(HD.NGHD) = 2020
)

----- 6
SELECT KH.HOTEN
FROM DBO.HOADON AS HD
    JOIN KHACHHANG AS KH ON HD.MAKH= KH.MAKH
WHERE YEAR(HD.NGHD)=2020 AND HD.TRIGIA >= ALL(
SELECT HD.TRIGIA
FROM DBO.HOADON AS HD
WHERE YEAR(HD.NGHD) = 2020
)

------- 7
SELECT COUNT(SP.MASP) AS [TONG SO SAN PHAM DO VIET NAM SAN XUAT]
FROM DBO.SANPHAM AS SP
WHERE NUOCSX='Viet Nam'

------- 8
SELECT SP.NUOCSX, COUNT(SP.MASP) AS [TONG SO SAN PHAM THEO TUNG NUOC SAN XUAT]
FROM DBO.SANPHAM AS SP
GROUP BY SP.NUOCSX

------- 9
SELECT SP.NUOCSX, MAX(SP.GIA) AS [GIA BAN CAO NHAT], MIN(SP.GIA) AS [GIA BAN THAP NHAT], AVG(SP.GIA) AS [GIA BAN TRUNG BINH]
FROM DBO.SANPHAM AS SP
GROUP BY SP.NUOCSX

------- 10
SELECT HD.NGHD, SUM(HD.TRIGIA) AS [DOANH THU]
FROM DBO.HOADON AS HD
GROUP BY HD.NGHD

------- 11
SELECT CT.MASP, SUM(SL) AS [TONG SO LUONG BAN RA]
FROM DBO.CTHD AS CT
    JOIN HOADON AS HD ON HD.SOHD= CT.SOHD
WHERE MONTH(HD.NGHD)=10 AND YEAR(HD.NGHD)=2020
GROUP BY CT.MASP

-------- 12
SELECT MONTH(HD.NGHD) AS [THANG], SUM(HD.TRIGIA) AS [DOANH THU]
FROM DBO.HOADON AS HD
WHERE YEAR(HD.NGHD)=2020
GROUP BY MONTH(HD.NGHD)

-------- 13
SELECT CT.SOHD
FROM DBO.CTHD AS CT
GROUP BY CT.SOHD
HAVING COUNT(CT.MASP)>=4

-------- 14
SELECT TOP 3 KH.MAKH, KH.HOTEN
FROM DBO.KHACHHANG AS KH
ORDER BY KH.DOANHSO DESC

-------- 15
SELECT SP.MASP, SP.TENSP
FROM DBO.SANPHAM AS SP
WHERE SP.GIA >= ANY (
SELECT DISTINCT TOP 3 SP.GIA
FROM DBO.SANPHAM AS SP
ORDER BY SP.GIA DESC
)
ORDER BY SP.GIA DESC

------- 16
SELECT SP.MASP, SP.TENSP
FROM DBO.SANPHAM AS SP
WHERE SP.NUOCSX='Thai Lan' AND SP.GIA >= ANY (
SELECT DISTINCT TOP 3 SP.GIA
FROM DBO.SANPHAM AS SP
ORDER BY SP.GIA DESC
)
ORDER BY SP.GIA DESC

-------- 17
SELECT SP.MASP, SP.TENSP
FROM DBO.SANPHAM AS SP
WHERE SP.NUOCSX='Viet Nam' AND SP.GIA >= ANY (
SELECT DISTINCT TOP 3 SP.GIA
FROM DBO.SANPHAM AS SP
WHERE SP.NUOCSX='Viet Nam'
ORDER BY SP.GIA DESC
)
ORDER BY SP.GIA DESC

------- 18
SELECT CT.SOHD
FROM DBO.CTHD AS CT
     JOIN DBO.SANPHAM  AS SP ON CT.MASP = SP.MASP
WHERE SP.NUOCSX= 'Viet Nam'
GROUP BY CT.SOHD
HAVING COUNT(CT.MASP)>=3

--------- 19
SELECT TOP 1 WITH TIES HD.MAKH, KH.HOTEN, COUNT(HD.SOHD) AS [SO LAN MUA HANG]
FROM DBO.HOADON AS HD
     JOIN DBO.KHACHHANG AS KH ON HD.MAKH=KH.MAKH
GROUP BY HD.MAKH, KH.HOTEN
ORDER BY COUNT(HD.SOHD) DESC

-------- 20.
SELECT TOP 1 MONTH(HD.NGHD) AS [THANG], SUM(HD.TRIGIA) AS [DOANH SO]
FROM DBO.HOADON AS HD
GROUP BY MONTH(HD.NGHD)
ORDER BY SUM(HD.TRIGIA) DESC

--------- 21.
SELECT TOP 1 SP.MASP, SP.TENSP, SUM(CT.SL) AS [TONG SO LUONG]
FROM DBO.CTHD AS CT
     JOIN DBO.HOADON AS HD ON CT.SOHD=HD.SOHD
	 RIGHT JOIN DBO.SANPHAM AS SP ON CT.MASP = SP.MASP
WHERE YEAR(HD.NGHD)=2007
GROUP BY CT.MASP, SP.MASP, SP.TENSP
ORDER BY SUM(CT.SL)

-------- 22
SELECT SP.NUOCSX
FROM DBO.SANPHAM AS SP
GROUP BY SP.NUOCSX
HAVING COUNT(DISTINCT SP.GIA)>=3

--------- 23
--- xem lai IN, can ket them 1 bang sanpham nuocsx=nuocsx, gia=gia
----- >=
SELECT SP.MASP, SP.TENSP, SP.NUOCSX
FROM DBO.SANPHAM AS SP
WHERE SP.GIA >= ALL (
SELECT MAX(SP1.GIA)
FROM DBO.SANPHAM AS SP1
WHERE SP1.NUOCSX=SP.NUOCSX 
GROUP BY SP1.NUOCSX
)

-------- 24
SELECT TOP 1 WITH TIES SP.MASP, SP.TENSP
FROM DBO.SANPHAM AS SP
WHERE SP.GIA < ALL(
SELECT MAX(SP1.GIA) 
FROM DBO.SANPHAM AS SP1
)
ORDER BY SP.GIA DESC

-------- 25
SELECT SP.MASP, SP.TENSP, SP
FROM DBO.SANPHAM AS SP
WHERE SP.GIA < ALL(
SELECT MAX(SP1.GIA) 
FROM DBO.SANPHAM AS SP1
) AND SP.GIA >= ANY (
SELECT DISTINCT TOP 3 SP2.GIA
FROM DBO.SANPHAM AS SP2
ORDER BY SP2.GIA DESC
)
ORDER BY SP.GIA DESC

--------- 26
