-------------- QUANLYGIAOVU -------------------
--9.	Lớp trưởng của một lớp phải là học viên của lớp đó.
--        Them   Xoa   Sua
--   LOP   +      -     +(MALOP,TRGLOP)
-- HOCVIEN -      +     +(MAHV,MALOP)
CREATE TRIGGER TRG_INSERT_UPDATE_LOP_TRGLOP ON LOP
FOR INSERT, UPDATE
AS
BEGIN
   IF EXISTS(SELECT *
            FROM INSERTED, HOCVIEN
			WHERE INSERTED.TRGLOP= HOCVIEN.MAHV AND INSERTED.MALOP=HOCVIEN.MALOP
			)
			BEGIN
			PRINT 'Them/Sua thanh cong'
			END
			ELSE
			BEGIN
			PRINT 'LOI: TRGLOP KHONG HOP LE'
			ROLLBACK TRANSACTION
			END
END
GO
CREATE TRIGGER TRG_UPDATE_HOCVIEN ON HOCVIEN
FOR UPDATE
AS
BEGIN
      IF EXISTS (SELECT * FROM DELETED, LOP, INSERTED
	             WHERE (INSERTED.MAHV = LOP.TRGLOP AND INSERTED.MALOP != DELETED.MALOP) OR (DELETED.MAHV=LOP.TRGLOP AND INSERTED.MAHV!=DELETED.MAHV) )
				 BEGIN
				 PRINT 'LOI: MA LOP KHONG HOP LE'
				 ROLLBACK TRANSACTION
				 END
      ELSE
	  BEGIN
	  PRINT 'Thay doi thanh cong'
	  END
END

GO
CREATE TRIGGER TRG_DELETE_HOCVIEN ON HOCVIEN
FOR DELETE
AS
BEGIN
       IF EXISTS(SELECT * FROM DELETED JOIN LOP ON DELETED.MALOP = LOP.MALOP
	             WHERE DELETED.MAHV = LOP.TRGLOP)
				 BEGIN
				 PRINT 'LOI: XOA THAT BAI'
				 ROLLBACK TRANSACTION
				 END
	  ELSE
	  BEGIN
	  PRINT 'XOA THANH CONG'
	  END
END
GO
--10.	Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”.
--           Them     Xoa    Sua
--KHOA         +       -      +(MAKHOA,TRGKHOA)
--GIAOVIEN     -       +      +(MAGV,MAKHOA)
CREATE TRIGGER TRG_INSERT_UPDATE_KHOA_TRGKHOA ON KHOA
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS(SELECT *
	          FROM INSERTED
			  JOIN GIAOVIEN GV ON GV.MAGV = INSERTED.TRGKHOA
			  WHERE GV.MAKHOA = INSERTED.MAKHOA AND (GV.HOCVI='TS' OR GV.HOCVI='PTS'))
			  BEGIN
			  PRINT 'THEM/THAY DOI KHOA THANH CONG'
			  END
	ELSE
	BEGIN
	PRINT 'LOI: TRUONG KHOA KHONG HOP LE'
	ROLLBACK TRANSACTION
	END
END
GO

CREATE TRIGGER TRG_UPDATE_GIAOVIEN_MAKHOA ON GIAOVIEN
FOR UPDATE
AS
BEGIN
       IF EXISTS (SELECT * FROM INSERTED JOIN KHOA ON KHOA.TRGKHOA= INSERTED.MAGV
	              WHERE (INSERTED.MAKHOA != KHOA.MAKHOA)				  
				  )
				  BEGIN
				  PRINT 'LOI: MA KHOA KHONG HOP LE'
				  ROLLBACK TRANSACTION
				  END
		ELSE
		BEGIN
		PRINT 'THAY DOI THANH CONG'
		END
END
GO
			  
CREATE TRIGGER TRG_DELETE_GIAOVIEN_MAKHOA ON GIAOVIEN
FOR DELETE
AS
BEGIN
       IF EXISTS (SELECT * FROM DELETED JOIN KHOA ON KHOA.MAKHOA=DELETED.MAKHOA
	              WHERE KHOA.TRGKHOA = DELETED.MAGV
				  )
				  BEGIN
				  PRINT 'LOI: XOA KHONG THANH CONG'
				  ROLLBACK TRANSACTION
				  END
		ELSE
		BEGIN
		PRINT 'XOA THANH CONG'
		END
END
GO
--15.	Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này.
--                THEM    XOA     SUA
--HOCVIEN           -      -       +(MAHV,MALOP)
--GIANGDAY          +      +       +(MALOP,MAMH,DENNGAY)
--KETQUATHI         +      -       +(MAHV,MAMH,NGTHI)
CREATE TRIGGER TRG_UPDATE_HOCVIEN_MALOP ON HOCVIEN
FOR UPDATE
AS
BEGIN
      IF EXISTS (SELECT * FROM INSERTED JOIN GIANGDAY GD ON GD.MALOP=INSERTED.MALOP JOIN KETQUATHI KQ ON KQ.MAHV=INSERTED.MAHV
	              WHERE GD.MAMH=KQ.MAMH AND GD.DENNGAY>KQ.NGTHI)
				  BEGIN
				  PRINT 'LOI: THAY DOI KHONG THANH CONG'
				  ROLLBACK TRANSACTION
				  END
	  ELSE
	  BEGIN
	  PRINT 'THAY DOI THANH CONG'
	  END
END
GO

CREATE TRIGGER TRG_INSERT_UPDATE_GIANGDAY ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
      IF EXISTS (SELECT * FROM INSERTED INS, HOCVIEN HV, KETQUATHI KQ
	             WHERE INS.MALOP=HV.MALOP AND INS.MAMH=KQ.MAMH AND HV.MAHV=KQ.MAHV AND INS.DENNGAY>KQ.NGTHI
				 )
				 BEGIN
				 PRINT 'LOI: THEM/THAY DOI KHONG THANH CONG'
				 ROLLBACK TRANSACTION
				 END
	 ELSE
	 BEGIN
	 PRINT 'THEM/THAY DOI THANH CONG'
	 END
END
GO

CREATE TRIGGER TRG_DELETE_GIANGDAY ON GIANGDAY
FOR DELETE
AS
BEGIN
       IF EXISTS( SELECT * FROM DELETED DEL, KETQUATHI KQ, HOCVIEN HV
	              WHERE KQ.MAHV=HV.MAHV AND DEL.MALOP=HV.MALOP AND DEL.MAMH = KQ.MAMH)
				  BEGIN
				  PRINT 'LOI: XOA KHONG THANH CONG'
				  ROLLBACK TRANSACTION
				  END
	  ELSE
	  BEGIN
	  PRINT 'XOA THANH CONG'
	  END
END
GO

CREATE TRIGGER TRG_INSERT_UPDATE_KETQUATHI ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
       IF EXISTS (SELECT  * FROM INSERTED INS, HOCVIEN HV, GIANGDAY GD
	              WHERE INS.MAHV=HV.MAHV AND HV.MALOP=GD.MALOP AND INS.MAMH = GD.MAMH AND INS.NGTHI< GD.DENNGAY
				 )
				 BEGIN
				 PRINT 'LOI: NGTHI KHONG HOP LE'
				 ROLLBACK TRANSACTION
				 END
		ELSE
		BEGIN
		PRINT 'THEM/THAY DOI THANH CONG'
		END
END
GO

--16.	Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn.
--             THEM     XOA    SUA
--GIANGDAY       +       -      +(MALOP,MAMH,HOCKY
CREATE TRIGGER TRG_INSERT_UPDATE_GIANGDAY_HOCKY ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
      IF EXISTS(SELECT * FROM INSERTED INS, GIANGDAY GD
	            WHERE INS.MALOP=GD.MALOP AND INS.HOCKY=GD.HOCKY
				GROUP BY GD.MALOP, GD.HOCKY
				HAVING COUNT(DISTINCT GD.MAMH)>3)
				BEGIN
				PRINT 'LOI: THEM/SUA KHONG THANH CONG'
				ROLLBACK TRANSACTION
				END
	 ELSE
	 BEGIN
	 PRINT 'THEM/SUA THANH CONG'
	 END
END
GO

--17.	Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó.
--           Them    Xoa    Sua
-- LOP         +      -      +(MALOP,SISO)
--HOCVIEN      +      +      +(MALOP)
CREATE TRIGGER TRG_INSERT_LOP_SISO ON LOP
FOR INSERT
AS 
BEGIN
      UPDATE LOP
	  SET SISO=0
	  FROM LOP JOIN INSERTED INS ON INS.MALOP= LOP.MALOP
      PRINT 'DA CAP NHAT SI SO LOP'
END
GO

CREATE TRIGGER TRG_UPDATE_LOP_SISO ON LOP
FOR UPDATE
AS
BEGIN
        IF EXISTS(SELECT * FROM INSERTED INS
		          WHERE INS.SISO!= (
				  SELECT COUNT(HV.MAHV) FROM HOCVIEN HV WHERE HV.MALOP=INS.MALOP
				  ))
				  BEGIN
				  PRINT 'LOI: SISO KHONG HOP LE'
				  ROLLBACK TRANSACTION
				  END
		ELSE
		BEGIN
		PRINT 'SUA THANH CONG'
		END
END
GO

CREATE TRIGGER TRG_INSERT_DELETE_UPDATE_HOCVIEN_SISO ON HOCVIEN
FOR INSERT, DELETE, UPDATE
AS
BEGIN
        UPDATE LOP
		SET SISO= (SELECT COUNT(HV.MAHV) FROM HOCVIEN HV WHERE HV.MALOP= LOP.MALOP)
		FROM INSERTED INS, DELETED DEL, LOP
		WHERE INS.MALOP = LOP.MALOP OR DEL.MALOP=LOP.MALOP
		PRINT 'CAP NHAT SISO THANH CONG'
END
GO
--18.	Trong quan hệ DIEUKIEN giá trị của thuộc tính MAMH và MAMH_TRUOC trong cùng một bộ không được giống nhau (“A”,”A”) và cũng không tồn tại hai bộ (“A”,”B”) và (“B”,”A”).
--     Them    Xoa   Sua
--DK    +       -     +(MAMH,MAMH_TRUOC)
CREATE TRIGGER TRG_INSERT_UPDATE_DIEUKIEN_MAMH_MAMH_TRUOC ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
       IF EXISTS(SELECT * FROM INSERTED INS
	             WHERE INS.MAMH!=INS.MAMH_TRUOC AND EXISTS (
				 SELECT * FROM DIEUKIEN DK WHERE DK.MAMH=INS.MAMH_TRUOC AND DK.MAMH_TRUOC=INS.MAMH
				 ))
				 BEGIN
				 PRINT 'LOI: MAMH VA MAMH_TRUOC KHONG HOP LE'
				 ROLLBACK TRANSACTION
				 END
		ELSE
		BEGIN
		PRINT 'THEM/SUA THANH CONG'
		END
END
GO
--19.	Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau.
--          Them     Xoa     Sua
--GIAOVIEN    +       -        +(HOCVI,HOCHAM,HESO,MUCLUONG)
CREATE TRIGGER TRG_INSERT_UPDATE_GIAOVIEN_MUCLUONG ON GIAOVIEN
FOR INSERT, UPDATE
AS
BEGIN
       IF EXISTS( SELECT * FROM INSERTED INS, GIAOVIEN GV
	               WHERE INS.HOCVI= GV.HOCVI AND INS.HOCHAM = GV.HOCHAM AND INS.HESO=GV.HESO AND INS.MUCLUONG!=GV.MUCLUONG)
				   BEGIN
				   PRINT 'LOI: MUC LUONG KHONG HOP LE'
				   ROLLBACK TRANSACTION
				   END
		ELSE
		BEGIN
		PRINT 'THEM/SUA THANH CONG'
		END
END
	   
GO
--20.	Học viên chỉ được thi lại (lần thi >1) khi điểm của lần thi trước đó dưới 5.
--           Them    Xoa   Sua
--KETQUATHI    +      -     +(MAHV,MAMH,LANTHI,DIEM)
CREATE TRIGGER TRG_INSERT_UPDATE_KETQUATHI_LANTHI ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
       IF EXISTS(SELECT * FROM INSERTED INS, KETQUATHI KQ
	             WHERE KQ.MAHV = INS.MAHV AND KQ.MAMH = INS.MAMH AND (KQ.LANTHI < INS.LANTHI AND KQ.DIEM >= 5) OR (KQ.LANTHI > INS.LANTHI AND INS.DIEM>=5)
	            )
				BEGIN
				PRINT 'LOI: LAN THI KHONG HOP LE'
				ROLLBACK TRANSACTION
				END
	ELSE 
	BEGIN 
	PRINT 'THEM/SUA THANH CONG'
	END
END
GO


--21.	Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước (cùng học viên, cùng môn học).
--           Them    Xoa   Sua
--KETQUATHI    +      -     +(MAHV,MAMH,LANTHI,NGTHI)
CREATE TRIGGER TRG_INSERT_UPDATE_KETQUATHI_NGAYTHI ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
       IF EXISTS(SELECT * FROM INSERTED INS, KETQUATHI KQ
	             WHERE KQ.MAHV = INS.MAHV AND KQ.MAMH = INS.MAMH AND (KQ.LANTHI < INS.LANTHI AND KQ.NGTHI > INS.NGTHI) OR (KQ.LANTHI > INS.LANTHI AND KQ.NGTHI<INS.NGTHI)
	            )
				BEGIN
				PRINT 'LOI: NGTHI KHONG HOP LE'
				ROLLBACK TRANSACTION
				END
	ELSE 
	BEGIN 
	PRINT 'THEM/SUA THANH CONG'
	END
END
GO
--22.	Khi phân công giảng dạy một môn học, phải xét đến thứ tự trước sau giữa các môn học (sau khi học xong những môn học phải học trước mới được học những môn liền sau).
--          Them    Xoa    Sua
--GIANGDAY    +      +      +(MALOP,MAMH,TUNGAY,DENNGAY)
CREATE TRIGGER TRG_INSERT_GIANGDAY_MAMH ON GIANGDAY
FOR INSERT
AS
BEGIN
       IF EXISTS(SELECT * FROM INSERTED INS JOIN DIEUKIEN DK ON INS.MAMH= DK.MAMH JOIN GIANGDAY GD ON (GD.MALOP=INS.MALOP AND GD.MAMH=DK.MAMH_TRUOC)
	             WHERE  INS.TUNGAY < GD.DENNGAY
	            )
				BEGIN
				PRINT 'LOI: THEM KHONG THANH CONG'
				ROLLBACK TRANSACTION
				END
		ELSE
		BEGIN
		PRINT 'THEM THANH CONG'
		END
END
GO

CREATE TRIGGER TRG_DELETE_GIANGDAY_MAMH ON GIANGDAY
FOR DELETE
AS
BEGIN
       IF EXISTS(SELECT * FROM DELETED DEL JOIN DIEUKIEN DK ON DEL.MAMH= DK.MAMH_TRUOC JOIN GIANGDAY GD ON (GD.MALOP=DEL.MALOP AND GD.MAMH=DK.MAMH)
	            )
				BEGIN
				PRINT 'LOI: XOA KHONG THANH CONG'
				ROLLBACK TRANSACTION
				END
		ELSE
		BEGIN
		PRINT 'XOA THANH CONG'
		END
END
GO

CREATE TRIGGER TRG_UPDATE_GIANGDAY_MAMH ON GIANGDAY
FOR UPDATE
AS
BEGIN
       IF EXISTS((SELECT * FROM INSERTED INS1 JOIN DIEUKIEN DK1 ON INS1.MAMH= DK1.MAMH_TRUOC JOIN GIANGDAY GD1 ON (GD1.MALOP=INS1.MALOP AND GD1.MAMH=DK1.MAMH))
	             UNION (SELECT * FROM DELETED DEL JOIN DIEUKIEN DK ON DEL.MAMH= DK.MAMH_TRUOC JOIN GIANGDAY GD ON (GD.MALOP=DEL.MALOP AND GD.MAMH=DK.MAMH))
	             )
				BEGIN
				PRINT 'LOI: SUA KHONG THANH CONG'
				ROLLBACK TRANSACTION
				END
		ELSE
		BEGIN
		PRINT 'SUA THANH CONG'
		END
END
GO
--23.	Giáo viên chỉ được phân công dạy những môn thuộc khoa giáo viên đó phụ trách.
--           Them   Xoa   Sua
--GIAOVIEN     -     -     +(MAGV,MAKHOA)
--MONHOC       -     -     +(MAMH,MAKHOA)
--GIANGDAY     +     -     +(MAMH,MAGV)
CREATE TRIGGER TRG_UPDATE_GIAOVIEN_PHANCONG ON GIAOVIEN
FOR UPDATE
AS
BEGIN
       IF EXISTS(SELECT * FROM INSERTED INS JOIN GIANGDAY GD ON GD.MAGV=INS.MAGV JOIN MONHOC MH ON MH.MAMH=GD.MAMH
	             WHERE INS.MAKHOA!=MH.MAKHOA)
				 BEGIN
				 PRINT 'LOI: MAKHOA CUA GIAOVIEN KHONG HOP LE'
				 ROLLBACK TRANSACTION
				 END
	   ELSE
	   BEGIN
	   PRINT 'SUA THANH CONG'
	   END
END
GO

CREATE TRIGGER TRG_UPDATE_MONHOC_PHANCONG ON MONHOC
FOR UPDATE
AS
BEGIN
     IF EXISTS(SELECT * FROM INSERTED INS JOIN GIANGDAY GD ON GD.MAMH=INS.MAMH JOIN GIAOVIEN GV ON GD.MAGV=GV.MAGV
	            WHERE INS.MAKHOA != GV.MAKHOA)
				BEGIN
				PRINT 'LOI: MAKHOA KHONG HOP LE'
				ROLLBACK TRANSACTION
				END
	ELSE
	BEGIN
	PRINT 'SUA THANH CONG'
	END
END
GO

CREATE TRIGGER TRG_INSERT_UPDATE_GIANGDAY_PHANCONG ON GIANGDAY
FOR INSERT,UPDATE
AS
BEGIN
       IF EXISTS(SELECT * FROM INSERTED INS JOIN GIAOVIEN GV ON INS.MAGV=GV.MAGV JOIN MONHOC MH ON INS.MAMH=MH.MAMH
	              WHERE GV.MAKHOA!=MH.MAKHOA)
				  BEGIN
				  PRINT 'LOI: THEM/SUA KHONG THANH CONG'
				  ROLLBACK TRANSACTION
				  END
		ELSE
		BEGIN
		PRINT 'THEM/SUA THANH CONG'
		END
END